ARDUINO_LIBS      := Wire
ARDUINO_PORT      := /dev/ttyACM0
USER_LIB_PATH     := $(realpath $(HOME)/sketchbook/libraries/)

BOARD_TAG         := Xadow
BOARDS_TXT        := $(HOME)/sketchbook/hardware/xadow/boards.txt

#ARDUINO_VAR_PATH  := $(realpath $(HOME)/sketchbook/hardware/xadow/)
#ARDUINO_CORE_PATH := $(realpath $(HOME)/sketchbook/hardware/xadow/)


CXXFLAGS      += -std=gnu++11
CFLAGS        += -std=gnu++11

include /usr/share/arduino/Arduino.mk
